# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""
Reloadable RayCaster Camera implementation for dynamic mesh support.
"""

import numpy as np
import omni.log
import omni.usd
from collections.abc import Sequence
import warp as wp

from isaaclab.sensors.ray_caster import RayCasterCamera, RayCasterCameraCfg
from isaaclab.utils.warp import convert_to_warp_mesh
from pxr import UsdGeom
from isaaclab.utils import configclass

class ReloadableRayCasterCamera(RayCasterCamera):
    """A ray-casting camera sensor with dynamic mesh reload capability.

    This class extends the standard RayCasterCamera to support dynamic mesh updates
    during simulation runtime. This is essential for environments where the terrain
    or obstacles change dynamically.
    """

    cfg: RayCasterCameraCfg
    """The configuration parameters."""

    def __init__(self, cfg: RayCasterCameraCfg):
        """Initialize the reloadable ray-caster camera.

        Args:
            cfg: The configuration parameters.
        """
        super().__init__(cfg)
        # Track if meshes need reloading
        self._mesh_reload_requested = False

    def reload_meshes(self) -> bool:
        """Reload the meshes from the current stage state.

        This method clears existing warp meshes and recreates them from the current
        USD stage geometry. This is necessary when the terrain/obstacles change
        during simulation.

        Returns:
            True if meshes were successfully reloaded, False otherwise.
        """
        try:
            # Clear existing meshes
            old_mesh_count = len(self.meshes)
            self.meshes.clear()

            # Force garbage collection of old warp meshes
            import gc
            gc.collect()

            # Reload meshes using the same logic as initialization
            self._initialize_warp_meshes()

            # Clear the reload request flag
            self._mesh_reload_requested = False

            # Clear any cached ray casting results by resetting buffers if they exist
            if hasattr(self, 'ray_hits_w'):
                self.ray_hits_w.zero_()

            # Reset sensor outdated flags to ensure fresh data on next access
            if hasattr(self, '_is_outdated'):
                self._is_outdated.fill_(True)

            omni.log.info(
                f"Successfully reloaded {len(self.meshes)} mesh(es) for RayCasterCamera "
                f"(was {old_mesh_count})"
            )
            return True

        except Exception as e:
            omni.log.error(f"Failed to reload meshes for RayCasterCamera: {e}")
            return False

    def request_mesh_reload(self):
        """Request a mesh reload on the next update cycle.

        This is a thread-safe way to request mesh reloading from external code.
        The actual reload will happen during the next sensor update.
        """
        self._mesh_reload_requested = True

    def _update_buffers_impl(self, env_ids: Sequence[int]):
        """Override to handle mesh reloading before ray casting.

        Args:
            env_ids: The indices of the sensors that are ready to capture.
        """
        # Check if mesh reload is requested
        if self._mesh_reload_requested:
            self.reload_meshes()

        # Proceed with normal buffer update
        super()._update_buffers_impl(env_ids)

    def _initialize_warp_meshes(self):
        """Initialize or reinitialize warp meshes from unified map mesh.

        This method is called during initialization and when reloading meshes.
        It directly reads the unified mesh generated by the map generator.
        """
        # Expecting single unified mesh from map generator
        if len(self.cfg.mesh_prim_paths) != 1:
            raise NotImplementedError(
                f"ReloadableRayCasterCamera currently only supports one mesh prim. "
                f"Received: {len(self.cfg.mesh_prim_paths)}"
            )

        mesh_prim_path = self.cfg.mesh_prim_paths[0]

        # Get the mesh prim directly (it's already a unified mesh from map generator)
        stage = omni.usd.get_context().get_stage()
        mesh_prim = stage.GetPrimAtPath(mesh_prim_path)

        if not mesh_prim.IsValid():
            raise RuntimeError(f"Mesh prim not found at path: {mesh_prim_path}")

        # Cast to UsdGeomMesh and read geometry data
        mesh_geom = UsdGeom.Mesh(mesh_prim)

        # Read the vertices and faces
        points = np.asarray(mesh_geom.GetPointsAttr().Get())
        indices = np.asarray(mesh_geom.GetFaceVertexIndicesAttr().Get())

        if points is None or len(points) == 0 or indices is None or len(indices) == 0:
            raise RuntimeError(f"Invalid mesh data at path: {mesh_prim_path}")

        # Apply world transformation
        transform_matrix = np.array(omni.usd.get_world_transform_matrix(mesh_prim)).T
        points = np.matmul(points, transform_matrix[:3, :3].T)
        points += transform_matrix[:3, 3]

        # Convert to warp mesh
        wp_mesh = convert_to_warp_mesh(points, indices, device=self.device)

        # Store the mesh
        self.meshes[mesh_prim_path] = wp_mesh

        omni.log.info(
            f"Loaded unified mesh: {mesh_prim.GetPath()} with {len(points)} vertices "
            f"and {len(indices)} faces."
        )

@configclass
class ReloadableRayCasterCameraCfg(RayCasterCameraCfg):
    """Configuration for the reloadable ray-caster camera."""

    class_type: type = ReloadableRayCasterCamera
    """The class type to instantiate. Default is ReloadableRayCasterCamera."""